; M5Stack Atom Lite - trigger MQTT
; Compilar y flashear:  pio run -t upload && pio device monitor
[env:atom]
platform      = espressif32@6.8.1
board         = m5stack-atom
framework     = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

; Si la autodeteccion falla, descomenta (tu Atom aparecio como COM6):
; upload_port = COM6
; monitor_port = COM6

build_flags =
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    m5stack/M5Unified@^0.2.2
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.2.0
